### ISSUE TITLE
Metanorma document manifest / index

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-mpfd#3]
Here's a document manifest / index created by @pierrefortier .

I wonder what's the best way to create this. A YAML/JSON/XML file? An AsciiDoctor file?

Thoughts @opoudjis ?

[index-guidelines.zip](https://github.com/riboseinc/metanorma-mpfd/files/2322025/index-guidelines.zip)

**Comment by ronaldtse** [comment]
Food for thought:

* Should we have a manifest file that can link to remote Metanorma files (i.e. the child documents can be stored elsewhere)?
* Should this manifest directly include content from the child Metanorma files? i.e. if I click on a child metanorma document A, that links to child metanorma document B, I don't get switched away to another site? (i.e. it should always keep my context that I am at the parent metanorma document)
* Should the child Metanorma files be automatically built, or is this out of scope?

To me they are, Yes, Yes and No.

Thanks!

**Comment by opoudjis** [comment]
I'm relieved. I thought you wanted some elaborate unworkable cross-linking scheme (and if you do want cross-linking, better to just put the HTML ID anchors in, like Asciidoctor does natively, rather than try to reverse engineer them from citations). But this is just going to end up as include links.

This can be done as JSON (I wouldn't bother with YAML or XML), or it can be done as Asciidoctor. Asciidoctor is attractive, because you can do some formatting around the inclusions.

Of your dot points, don't A and B contradict each other? If the manifest points to local files, then of course you won't go to another site. The manifest should probably not re-cite the asciidoctor source (bad for maintenance); and if it does, you might as well do C as well. But the proper way to do this is as links to external documents.

Let me see if we can get this done in Asciidoctor.

**Comment by opoudjis** [comment]
Asciidoctor includes resolve, which is not what we want: we want them to stay as hyperlinks. I propose we implement a macro. We include a file description and filename in the macro; in HTML mode, it's hyperlinks to the file name in HTML, using the file description as link text. In Word mode, it just presents the file description text.

**Comment by ronaldtse** [comment]
The first two questions shouldn’t be contradictory, since the feature in the first question could be optional. 

However your comment did bring up an interesting topic. Should we have something called “Metanorma collection” in XML?

Currently all Metanorma documents are monographs. Maybe there could be serials or multi-part (!) documents? For example, the 690xml scheme correctly models them.

**Comment by opoudjis** [comment]
This doesn't really do serials, this is just a bunch of hyperlinks in a document. Serials are serials because they are labelled as such, not because they are hyperlinked.

Given https://github.com/riboseinc/metanorma-iso/issues/208, I don't think we need even a macro: just the link to the HTML child document, with citation text. Of course, that presupposes the location of the child document is predictable, and that you have determined in advance where the child documents are going to live. But why wouldn't you?

That solution requires zero additional work; you'll have to tell me if it meets your functional requirements. I may or may not be missing something.

**Comment by ronaldtse** [comment]
So one of the arguments that Metanorma is better is because it is semantically aware. If they purely link in HTML, there are no semantics. i.e. if I want to represent a set of standards (which is quite often, say a management system manual that is composed of policies and procedures), it can only be stitched together using HTML, not Metanorma.

Ideally we should have Metanorma XML files that should get linked together, and a single command on those Metanorma XML files can generate the whole hierarchy.

**Comment by opoudjis** [comment]
So an XML file with a bunch of xi: includes, which is still somehow postprocessed to generate something that looks like Pierre's output, but without using asciidoctor?

if you're not going to build from this file, and if the hyperlinks are only realised in the HTML conversion of the file, I don't see that the semantic relation buys you that much. I need more functional requirements.

**Comment by opoudjis** [comment]
I clearly still need requirements here. 

* Is the output going to look like a Metanorma document in the given standard style, or is it just a set of HTML links?
* Is it going to include extraneous text, or not?
* Is it expected to fish links out contained documents, or have the links embedded in the manifest file?
* Is this a build tool or merely a presentation tool? (You've contradicted yourself above.)

Whether this is going to be a YAML file or an Asciidoctor file depends on the answer to these questions. (XML and JSON are out: this is either an extremely simple list of files and links, or it is a formatted document containing links to files, which is postprocessed. JSON and XML are not something you want a human to write.)

Simplicity is a good thing, and a YAML starting point allows an Asciidoctor pretty document to be generated from it, as well as a build file. OTOH, fishing files out of Asciidoctor for processing will be unnecessarily complex. 

So I propose to start with a YAML file representing what you have above, then write a script that converts it into the kind of Asciidoctor that would generate the sample you got Pierre to make.

**Comment by opoudjis** [comment]
How about his? I've added anchors in for I.2:

````
title: Guidelines
sections:
  - number: Part I
    title: Licensing
    sections:
      - number: I.1
        title: Guidelines on Application for Approval as Trustees and Application for Approval as Controllers of Approved Trustees
        file: guidelines_I1.adoc
        revdate: 2014-10-17
        description: Section description.
        sections:
          - number: Annex A
            file: guidelines_I1A.adoc
          - number: Annex B
            file: guidelines_I1B.adoc
          - number: Annex C
            file: guidelines_I1C.adoc
      - number: I.2
        title: Guidelines on Application for Registration of Provident Fund Schemes
        file: guidelines_I2.adoc
        description: Section description.
        sections:
          - number: Clause 1
            file: guidelines_I1A.adoc#clause1
          - number: Clause 2
            file: guidelines_I1A.adoc#clause2
      - number: I.3
        title: Guidelines on Custodians
        file: guidelines_I3.adoc
        description: Section description.
      - number: I.4
        title: Guidelines on Eligible Insurers
        file: guidelines_I4.adoc
        description: Section description.
      - number: I.5
        title: Guidelines on Application for Approval of Constituent Funds
        file: guidelines_I5.adoc
        description: Section description.
  - number: Part II
    title: Reporting Requirements
    sections: 
      - number: II.1
        title: Guidelines on Monthly Returns of Registered Schemes
        file: guidelines_II1.adoc
        description: Section description.
      - number: II.2
        title: Guidelines on Monthly Returns of Approved Pooled Investment Funds being Capital Preservation Funds
        file: guidelines_II2.adoc
        description: Section description.
      - number: II.3
        title: Guidelines on Quarterly Statistical Returns of Registered Schemes
        file: guidelines_II3.adoc
        description: Section description.
    
````
